// eslint.config.mjs

import globals from "globals"
import js from "@eslint/js"
import tseslint from "typescript-eslint"
import nextPlugin from "@next/eslint-plugin-next"
import reactPlugin from "eslint-plugin-react"
import prettierConfig from "eslint-config-prettier"

const eslintConfig = [
    // 1. Global ignores — paths that ESLint should skip entirely.
    {
        ignores: [
            "node_modules/",
            ".next/",
            "out/",
            "build/",
            "dist/",
            "next-env.d.ts",
            // Auto-generated by `npm run types:generate` (json-schema-to-typescript).
            // The generator emits a `/* eslint-disable */` header that trips the
            // `report-unused-disable-directives` rule otherwise.
            "types/generated.ts/**",
            // Python sources — ESLint has nothing useful to say about these.
            "server/**",
            "tests/**",
            // User-specific Claude Code settings.
            ".claude/**",
        ],
    },

    // 2. Baseline recommended ESLint rules for every remaining file.
    js.configs.recommended,

    // 3. TypeScript rules — scoped to .ts/.tsx so plain .js/.mjs scripts
    //    don't get TS-specific bans like @typescript-eslint/no-require-imports.
    ...tseslint.configs.recommended.map((config) => ({
        ...config,
        files: ["**/*.{ts,tsx}"],
    })),

    // 4. React + Next.js + browser/node globals for the Next.js app source.
    {
        files: ["**/*.{js,jsx,ts,tsx}"],
        plugins: {
            "@next/next": nextPlugin,
            react: reactPlugin,
        },
        languageOptions: {
            parserOptions: {
                ecmaFeatures: {
                    jsx: true,
                },
            },
            globals: {
                ...globals.browser,
                ...globals.node,
                JSX: "readonly",
            },
        },
        rules: {
            ...nextPlugin.configs["core-web-vitals"].rules,
            "react/prop-types": "off",
            "react/react-in-jsx-scope": "off",
        },
        settings: {
            react: {
                version: "detect",
            },
        },
    },

    // 5. Plain Node scripts in scripts/ and data/ — they are .mjs / .js,
    //    may use CommonJS `require()`, and run under Node so they need the
    //    Node globals explicitly.
    {
        files: ["scripts/**/*.{js,mjs,cjs}", "data/**/*.{js,mjs,cjs}"],
        languageOptions: {
            sourceType: "module",
            globals: {
                ...globals.node,
            },
        },
        rules: {
            // These files are intentionally plain Node — do not force ESM-only
            // import syntax on them.
            "@typescript-eslint/no-require-imports": "off",
            "no-undef": "off",
            // Allow `catch (err) { /* swallow */ }` in these utility scripts.
            "no-unused-vars": [
                "error",
                {
                    args: "after-used",
                    argsIgnorePattern: "^_",
                    caughtErrors: "none",
                },
            ],
        },
    },

    // 6. Prettier — MUST be last so it can turn off any conflicting style rules.
    prettierConfig,
]

export default eslintConfig
