/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A key-value map where each key is a recipe identifier and the value is its corresponding chapter identifier. This format is optimized for fast lookups.
 */
export interface RecipeDictionaryMap {
  /**
   * The value must be a chapter identifier string, e.g., 'chapter-i'.
   *
   * This interface was referenced by `RecipeDictionaryMap`'s JSON-Schema definition
   * via the `patternProperty` "^\d+[a-zA-Z]?$".
   */
  [k: string]: string;
}
