/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The table of contents for the cookbook, organized into parts and chapters.
 */
export type CookbookTableOfContents = PartEntry[];

/**
 * A major part of the cookbook, containing a title and a list of chapters.
 */
export interface PartEntry {
  /**
   * The part number, expressed as a Roman numeral.
   */
  part: string;
  /**
   * The title of the part.
   */
  title: string;
  chapters: ChapterEntry[];
  [k: string]: unknown;
}
export interface ChapterEntry {
  /**
   * The chapter number, expressed as a Roman numeral.
   */
  chapter: string;
  /**
   * A machine-readable identifier for building hyperlinks (e.g., 'chapter-i').
   */
  id: string;
  /**
   * The title of the chapter.
   */
  title: string;
  [k: string]: unknown;
}
