/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a piece of information that can be a simple string, an array of strings for paragraphs, or a titled object with a list of detail strings.
 */
export type ContentBlock =
  | string
  | {
      [k: string]: string[];
    }
  | string[];
