/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Can be either a standard term or a cross-reference.
 */
export type IndexEntry = IndexTerm | IndexCrossReference;
/**
 * An index for the cookbook, grouped alphabetically.
 */
export type CookbookIndex = IndexGroup[];

/**
 * A group of index entries under a specific letter of the alphabet.
 */
export interface IndexGroup {
  letter: string;
  entries: IndexEntry[];
  [k: string]: unknown;
}
export interface IndexTerm {
  /**
   * The indexed term or phrase.
   */
  term: string;
  /**
   * The associated recipe number or range (e.g., '1652' or '2104-6').
   */
  recipe_number?: string;
  [k: string]: unknown;
}
export interface IndexCrossReference {
  /**
   * The term to be redirected.
   */
  term: string;
  /**
   * The term to which the user is redirected (e.g., 'Apricots').
   */
  see: string;
  [k: string]: unknown;
}
