/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a single course in a menu, which can be a simple string or a choice between multiple options.
 */
export type MenuItem =
    | string
    | {
          /**
           * @minItems 2
           */
          choice: [string, string, ...string[]]
          [k: string]: unknown
      }
/**
 * A collection of menus, which can be grouped into sets.
 */
export type CookbookMenus = MenuCollection[]

/**
 * A titled group of menus, like 'Menus for Luncheons'.
 */
export interface MenuCollection {
    title: string
    menus: Menu[]
    [k: string]: unknown
}
/**
 * A single menu, containing a list of food items, an optional wine list, and optional metadata.
 */
export interface Menu {
    title?: string
    items?: MenuItem[]
    wines?: string[]
    metadata?: {
        date?: string
        location?: string
        occasion?: string
        [k: string]: unknown
    }
    [k: string]: unknown
}
