/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a piece of information that can be a simple string or a titled object with a list of detail strings.
 */
export type ContentBlock =
    | string
    | {
          [k: string]: string[]
      }

/**
 * A standalone recipe entry.
 */
export interface Recipe {
    /**
     * The unique number of the recipe.
     */
    number: number
    /**
     * The title of the recipe.
     */
    title: string
    /**
     * The type of entry, which must be 'recipe'.
     */
    type: "recipe"
    introduction?: ContentBlock
    notes?: ContentBlock[]
    yield?: string
    ingredients: ContentBlock[]
    instructions: ContentBlock[]
    [k: string]: unknown
}
